//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntireCommodityCategory
    {
        public int CommodityCategoryID { get; set; }
        public string Name { get; set; }
        public string EntireName { get; set; }
        public int CommodityCategoryID1 { get; set; }
        public string Name1 { get; set; }
        public int CommodityCategoryID2 { get; set; }
        public string Name2 { get; set; }
        public int CommodityCategoryID3 { get; set; }
        public string Name3 { get; set; }
    }
}
