//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class HandlingUnitSheet
    {
        public int HandlingUnitID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string GoodsIssueReferences { get; set; }
        public int Identification { get; set; }
        public int CountIdentification { get; set; }
        public decimal TotalWeight { get; set; }
        public decimal RealWeight { get; set; }
        public string PackingMaterialPrintedLabel { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public string ShippingAddress { get; set; }
        public string ReceiverName { get; set; }
        public int ReceiverCategoryID { get; set; }
        public string ReceiverCategoryCode { get; set; }
        public string VendorCode { get; set; }
        public string VendorCategory { get; set; }
        public string PackagingStaffName { get; set; }
        public string Code { get; set; }
        public string CodePartA { get; set; }
        public string CodePartB { get; set; }
        public string CodePartC { get; set; }
        public string CodePartD { get; set; }
        public decimal Quantity { get; set; }
    }
}
