//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderDetail
    {
        public int PurchaseOrderDetailID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int LocationID { get; set; }
        public int PurchaseOrderID { get; set; }
        public int SupplierID { get; set; }
        public int ProjectID { get; set; }
        public Nullable<int> RequisitionOrderDetailID { get; set; }
        public int CommodityID { get; set; }
        public int CommodityTypeID { get; set; }
        public int SalespersonID { get; set; }
        public int CalculatingTypeID { get; set; }
        public decimal Quantity { get; set; }
        public decimal QuantityIssue { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal VATPercent { get; set; }
        public decimal GrossPrice { get; set; }
        public decimal Amount { get; set; }
        public decimal VATAmount { get; set; }
        public decimal GrossAmount { get; set; }
        public Nullable<bool> IsBonus { get; set; }
        public string RowCategory { get; set; }
        public string RowDescription { get; set; }
        public string RowSpecification { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> VoidTypeID { get; set; }
        public bool Approved { get; set; }
        public bool InActive { get; set; }
        public bool InActivePartial { get; set; }
        public Nullable<System.DateTime> InActivePartialDate { get; set; }
        public bool InActiveIssue { get; set; }
        public string RowUnit { get; set; }
        public string RequestNo { get; set; }
        public string JobType { get; set; }
        public string JobNo { get; set; }
        public string CodeSection { get; set; }
        public string CodeItem { get; set; }
    
        public virtual Commodity Commodity { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
